// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Empleado = sequelize.define('empleado', {
    idEmpleado: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    nombreUnico: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    numeroUsuario: {
      type: DataTypes.STRING,
      allowNull: false,
    },
  }, {
    tableName: 'Empleado',
    timestamps: false,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Empleado.associate = (models) => {
    Empleado.belongsTo(models.jefe, {
      foreignKey: {
        name: 'idJefeKey',
        field: 'idJefe',
      },
      targetKey: 'idJefe',
      as: 'idJefe',
    });
    Empleado.hasMany(models.historialFichas, {
      foreignKey: {
        name: 'idEmpleadoKey',
        field: 'idEmpleado',
      },
      sourceKey: 'idEmpleado',
      as: 'idEmpleadoHistorialFichas',
    });
  };

  return Empleado;
};
