// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const HistorialFichas = sequelize.define('historialFichas', {
    idFicha: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    latitud: {
      type: DataTypes.STRING,
    },
    longitud: {
      type: DataTypes.STRING,
    },
    fecha: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('current_timestamp()'),
      allowNull: false,
    },
    entrada: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    salida: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
  }, {
    tableName: 'HistorialFichas',
    timestamps: false,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  HistorialFichas.associate = (models) => {
    HistorialFichas.belongsTo(models.jefe, {
      foreignKey: {
        name: 'idJefeKey',
        field: 'idJefe',
      },
      targetKey: 'idJefe',
      as: 'idJefe',
    });
    HistorialFichas.belongsTo(models.empleado, {
      foreignKey: {
        name: 'idEmpleadoKey',
        field: 'idEmpleado',
      },
      targetKey: 'idEmpleado',
      as: 'idEmpleado',
    });
  };

  return HistorialFichas;
};
