// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Jefe = sequelize.define('jefe', {
    idJefe: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    usuario: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    password: {
      type: DataTypes.STRING,
      allowNull: false,
    },
  }, {
    tableName: 'Jefe',
    timestamps: false,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Jefe.associate = (models) => {
    Jefe.hasMany(models.empleado, {
      foreignKey: {
        name: 'idJefeKey',
        field: 'idJefe',
      },
      sourceKey: 'idJefe',
      as: 'idJefeEmpleados',
    });
    Jefe.hasMany(models.historialFichas, {
      foreignKey: {
        name: 'idJefeKey',
        field: 'idJefe',
      },
      sourceKey: 'idJefe',
      as: 'idJefeHistorialFichas',
    });
  };

  return Jefe;
};
